// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: pkg/pb/proto/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunningSpacesList_Status int32

const (
	RunningSpacesList_Success  RunningSpacesList_Status = 0
	RunningSpacesList_NotFound RunningSpacesList_Status = 1
)

// Enum value maps for RunningSpacesList_Status.
var (
	RunningSpacesList_Status_name = map[int32]string{
		0: "Success",
		1: "NotFound",
	}
	RunningSpacesList_Status_value = map[string]int32{
		"Success":  0,
		"NotFound": 1,
	}
)

func (x RunningSpacesList_Status) Enum() *RunningSpacesList_Status {
	p := new(RunningSpacesList_Status)
	*p = x
	return p
}

func (x RunningSpacesList_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunningSpacesList_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_proto_service_proto_enumTypes[0].Descriptor()
}

func (RunningSpacesList_Status) Type() protoreflect.EnumType {
	return &file_pkg_pb_proto_service_proto_enumTypes[0]
}

func (x RunningSpacesList_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunningSpacesList_Status.Descriptor instead.
func (RunningSpacesList_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{7, 0}
}

type ResourceLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu     string `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory  string `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage string `protobuf:"bytes,3,opt,name=Storage,proto3" json:"Storage,omitempty"`
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimit) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceLimit) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceLimit) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

type WorkspaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid             string         `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid             string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Image           string         `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Port            int32          `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	VolumeMountPath string         `protobuf:"bytes,5,opt,name=volumeMountPath,proto3" json:"volumeMountPath,omitempty"`
	Resourcelimit   *ResourceLimit `protobuf:"bytes,6,opt,name=resourcelimit,proto3" json:"resourcelimit,omitempty"`
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *WorkspaceInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WorkspaceInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WorkspaceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *WorkspaceInfo) GetVolumeMountPath() string {
	if x != nil {
		return x.VolumeMountPath
	}
	return ""
}

func (x *WorkspaceInfo) GetResourcelimit() *ResourceLimit {
	if x != nil {
		return x.Resourcelimit
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *QueryOption) Reset() {
	*x = QueryOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOption) ProtoMessage() {}

func (x *QueryOption) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOption.ProtoReflect.Descriptor instead.
func (*QueryOption) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryOption) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type WorkspaceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WorkspaceStatus) Reset() {
	*x = WorkspaceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatus) ProtoMessage() {}

func (x *WorkspaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatus.ProtoReflect.Descriptor instead.
func (*WorkspaceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *WorkspaceStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkspaceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkspaceRunningInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port     int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *WorkspaceRunningInfo) Reset() {
	*x = WorkspaceRunningInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceRunningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRunningInfo) ProtoMessage() {}

func (x *WorkspaceRunningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRunningInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceRunningInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceRunningInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *WorkspaceRunningInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WorkspaceRunningInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RunningSpacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RunningSpacesRequest) Reset() {
	*x = RunningSpacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSpacesRequest) ProtoMessage() {}

func (x *RunningSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSpacesRequest.ProtoReflect.Descriptor instead.
func (*RunningSpacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *RunningSpacesRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type RunningSpacesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspaces []*RunningSpacesList_WorkspaceBasicInfo `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
}

func (x *RunningSpacesList) Reset() {
	*x = RunningSpacesList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningSpacesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSpacesList) ProtoMessage() {}

func (x *RunningSpacesList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSpacesList.ProtoReflect.Descriptor instead.
func (*RunningSpacesList) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *RunningSpacesList) GetWorkspaces() []*RunningSpacesList_WorkspaceBasicInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type RunningSpacesList_WorkspaceBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RunningSpacesList_WorkspaceBasicInfo) Reset() {
	*x = RunningSpacesList_WorkspaceBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningSpacesList_WorkspaceBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSpacesList_WorkspaceBasicInfo) ProtoMessage() {}

func (x *RunningSpacesList_WorkspaceBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSpacesList_WorkspaceBasicInfo.ProtoReflect.Descriptor instead.
func (*RunningSpacesList_WorkspaceBasicInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_proto_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RunningSpacesList_WorkspaceBasicInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *RunningSpacesList_WorkspaceBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pkg_pb_proto_service_proto protoreflect.FileDescriptor

var file_pkg_pb_proto_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x53, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d,
	0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x37, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x14,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x28, 0x0a, 0x14, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xbe,
	0x01, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x3a,
	0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x32,
	0x9f, 0x03, 0x0a, 0x0a, 0x43, 0x43, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x67, 0x65,
	0x74, 0x50, 0x6f, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x47, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x70, 0x61, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_pb_proto_service_proto_rawDescOnce sync.Once
	file_pkg_pb_proto_service_proto_rawDescData = file_pkg_pb_proto_service_proto_rawDesc
)

func file_pkg_pb_proto_service_proto_rawDescGZIP() []byte {
	file_pkg_pb_proto_service_proto_rawDescOnce.Do(func() {
		file_pkg_pb_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_proto_service_proto_rawDescData)
	})
	return file_pkg_pb_proto_service_proto_rawDescData
}

var file_pkg_pb_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_pb_proto_service_proto_goTypes = []interface{}{
	(RunningSpacesList_Status)(0),                // 0: pb.RunningSpacesList.Status
	(*ResourceLimit)(nil),                        // 1: pb.ResourceLimit
	(*WorkspaceInfo)(nil),                        // 2: pb.WorkspaceInfo
	(*Response)(nil),                             // 3: pb.Response
	(*QueryOption)(nil),                          // 4: pb.QueryOption
	(*WorkspaceStatus)(nil),                      // 5: pb.WorkspaceStatus
	(*WorkspaceRunningInfo)(nil),                 // 6: pb.WorkspaceRunningInfo
	(*RunningSpacesRequest)(nil),                 // 7: pb.RunningSpacesRequest
	(*RunningSpacesList)(nil),                    // 8: pb.RunningSpacesList
	(*RunningSpacesList_WorkspaceBasicInfo)(nil), // 9: pb.RunningSpacesList.WorkspaceBasicInfo
}
var file_pkg_pb_proto_service_proto_depIdxs = []int32{
	1, // 0: pb.WorkspaceInfo.resourcelimit:type_name -> pb.ResourceLimit
	9, // 1: pb.RunningSpacesList.workspaces:type_name -> pb.RunningSpacesList.WorkspaceBasicInfo
	2, // 2: pb.CCPService.createSpace:input_type -> pb.WorkspaceInfo
	2, // 3: pb.CCPService.startSpace:input_type -> pb.WorkspaceInfo
	4, // 4: pb.CCPService.deleteSpace:input_type -> pb.QueryOption
	4, // 5: pb.CCPService.stopSpace:input_type -> pb.QueryOption
	4, // 6: pb.CCPService.getPodSpaceStatus:input_type -> pb.QueryOption
	4, // 7: pb.CCPService.getPodSpaceInfo:input_type -> pb.QueryOption
	7, // 8: pb.CCPService.getRunningWorkspaces:input_type -> pb.RunningSpacesRequest
	6, // 9: pb.CCPService.createSpace:output_type -> pb.WorkspaceRunningInfo
	6, // 10: pb.CCPService.startSpace:output_type -> pb.WorkspaceRunningInfo
	3, // 11: pb.CCPService.deleteSpace:output_type -> pb.Response
	3, // 12: pb.CCPService.stopSpace:output_type -> pb.Response
	5, // 13: pb.CCPService.getPodSpaceStatus:output_type -> pb.WorkspaceStatus
	6, // 14: pb.CCPService.getPodSpaceInfo:output_type -> pb.WorkspaceRunningInfo
	8, // 15: pb.CCPService.getRunningWorkspaces:output_type -> pb.RunningSpacesList
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_proto_service_proto_init() }
func file_pkg_pb_proto_service_proto_init() {
	if File_pkg_pb_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceRunningInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningSpacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningSpacesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningSpacesList_WorkspaceBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_proto_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_proto_service_proto_goTypes,
		DependencyIndexes: file_pkg_pb_proto_service_proto_depIdxs,
		EnumInfos:         file_pkg_pb_proto_service_proto_enumTypes,
		MessageInfos:      file_pkg_pb_proto_service_proto_msgTypes,
	}.Build()
	File_pkg_pb_proto_service_proto = out.File
	file_pkg_pb_proto_service_proto_rawDesc = nil
	file_pkg_pb_proto_service_proto_goTypes = nil
	file_pkg_pb_proto_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CCPServiceClient is the client API for CCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CCPServiceClient interface {
	CreateSpace(ctx context.Context, in *WorkspaceInfo, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error)
	StartSpace(ctx context.Context, in *WorkspaceInfo, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error)
	DeleteSpace(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*Response, error)
	StopSpace(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*Response, error)
	GetPodSpaceStatus(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*WorkspaceStatus, error)
	GetPodSpaceInfo(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error)
	GetRunningWorkspaces(ctx context.Context, in *RunningSpacesRequest, opts ...grpc.CallOption) (*RunningSpacesList, error)
}

type cCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCCPServiceClient(cc grpc.ClientConnInterface) CCPServiceClient {
	return &cCPServiceClient{cc}
}

func (c *cCPServiceClient) CreateSpace(ctx context.Context, in *WorkspaceInfo, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error) {
	out := new(WorkspaceRunningInfo)
	err := c.cc.Invoke(ctx, "/pb.CCPService/createSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) StartSpace(ctx context.Context, in *WorkspaceInfo, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error) {
	out := new(WorkspaceRunningInfo)
	err := c.cc.Invoke(ctx, "/pb.CCPService/startSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) DeleteSpace(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CCPService/deleteSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) StopSpace(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CCPService/stopSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) GetPodSpaceStatus(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*WorkspaceStatus, error) {
	out := new(WorkspaceStatus)
	err := c.cc.Invoke(ctx, "/pb.CCPService/getPodSpaceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) GetPodSpaceInfo(ctx context.Context, in *QueryOption, opts ...grpc.CallOption) (*WorkspaceRunningInfo, error) {
	out := new(WorkspaceRunningInfo)
	err := c.cc.Invoke(ctx, "/pb.CCPService/getPodSpaceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cCPServiceClient) GetRunningWorkspaces(ctx context.Context, in *RunningSpacesRequest, opts ...grpc.CallOption) (*RunningSpacesList, error) {
	out := new(RunningSpacesList)
	err := c.cc.Invoke(ctx, "/pb.CCPService/getRunningWorkspaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CCPServiceServer is the server API for CCPService service.
type CCPServiceServer interface {
	CreateSpace(context.Context, *WorkspaceInfo) (*WorkspaceRunningInfo, error)
	StartSpace(context.Context, *WorkspaceInfo) (*WorkspaceRunningInfo, error)
	DeleteSpace(context.Context, *QueryOption) (*Response, error)
	StopSpace(context.Context, *QueryOption) (*Response, error)
	GetPodSpaceStatus(context.Context, *QueryOption) (*WorkspaceStatus, error)
	GetPodSpaceInfo(context.Context, *QueryOption) (*WorkspaceRunningInfo, error)
	GetRunningWorkspaces(context.Context, *RunningSpacesRequest) (*RunningSpacesList, error)
}

// UnimplementedCCPServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCCPServiceServer struct {
}

func (*UnimplementedCCPServiceServer) CreateSpace(context.Context, *WorkspaceInfo) (*WorkspaceRunningInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpace not implemented")
}
func (*UnimplementedCCPServiceServer) StartSpace(context.Context, *WorkspaceInfo) (*WorkspaceRunningInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSpace not implemented")
}
func (*UnimplementedCCPServiceServer) DeleteSpace(context.Context, *QueryOption) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpace not implemented")
}
func (*UnimplementedCCPServiceServer) StopSpace(context.Context, *QueryOption) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSpace not implemented")
}
func (*UnimplementedCCPServiceServer) GetPodSpaceStatus(context.Context, *QueryOption) (*WorkspaceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodSpaceStatus not implemented")
}
func (*UnimplementedCCPServiceServer) GetPodSpaceInfo(context.Context, *QueryOption) (*WorkspaceRunningInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodSpaceInfo not implemented")
}
func (*UnimplementedCCPServiceServer) GetRunningWorkspaces(context.Context, *RunningSpacesRequest) (*RunningSpacesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunningWorkspaces not implemented")
}

func RegisterCCPServiceServer(s *grpc.Server, srv CCPServiceServer) {
	s.RegisterService(&_CCPService_serviceDesc, srv)
}

func _CCPService_CreateSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).CreateSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/CreateSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).CreateSpace(ctx, req.(*WorkspaceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_StartSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).StartSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/StartSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).StartSpace(ctx, req.(*WorkspaceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_DeleteSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).DeleteSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/DeleteSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).DeleteSpace(ctx, req.(*QueryOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_StopSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).StopSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/StopSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).StopSpace(ctx, req.(*QueryOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_GetPodSpaceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).GetPodSpaceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/GetPodSpaceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).GetPodSpaceStatus(ctx, req.(*QueryOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_GetPodSpaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).GetPodSpaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/GetPodSpaceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).GetPodSpaceInfo(ctx, req.(*QueryOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _CCPService_GetRunningWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunningSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCPServiceServer).GetRunningWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CCPService/GetRunningWorkspaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCPServiceServer).GetRunningWorkspaces(ctx, req.(*RunningSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CCPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CCPService",
	HandlerType: (*CCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createSpace",
			Handler:    _CCPService_CreateSpace_Handler,
		},
		{
			MethodName: "startSpace",
			Handler:    _CCPService_StartSpace_Handler,
		},
		{
			MethodName: "deleteSpace",
			Handler:    _CCPService_DeleteSpace_Handler,
		},
		{
			MethodName: "stopSpace",
			Handler:    _CCPService_StopSpace_Handler,
		},
		{
			MethodName: "getPodSpaceStatus",
			Handler:    _CCPService_GetPodSpaceStatus_Handler,
		},
		{
			MethodName: "getPodSpaceInfo",
			Handler:    _CCPService_GetPodSpaceInfo_Handler,
		},
		{
			MethodName: "getRunningWorkspaces",
			Handler:    _CCPService_GetRunningWorkspaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/proto/service.proto",
}
